root = "."

[build]
  args_bin = ["bootRun"]
  bin = "./gradlew"
  cmd = "echo reload!"
  delay = 0
  exclude_dir = ["build", "gradle"]
  include_dir = ["src"]
  include_ext = ["java"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
